import type { Playlist } from "../types/music";

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: "1",
    name: "Chill Songs",
    collaborators: ["xevrion", "chishxd"],
    coverUrl: "https://imgs.search.brave.com/rb6QTcHOPjBFH5o2e8rFd5oPOWVjvlnw_ssrLuFyuQg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2I3Lzll/LzRiL2I3OWU0YjJh/MDBhZTMwYmRmYmNk/ODc2ZmRiMTZkNWI2/LmpwZw",
    tracks: [
      {
        id: "1",
        title: "Blinding Lights",
        artist: "The Weeknd",
        album: "After Hours",
        addedAt: "3 days ago",
        duration: "3:20",
        coverUrl: "https://imgs.search.brave.com/50qdfEooh_HgzQR-zVMQlvpZsv1wUB7AffSfiv1naUQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnJl/ZGQuaXQvZXJ5djJu/bGhtZGc5MS5qcGc",
      },
      {
        id: "2",
        title: "Levitating",
        artist: "Dua Lipa",
        album: "Future Nostalgia",
        addedAt: "5 days ago",
        duration: "3:23",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "3",
        title: "Stay",
        artist: "The Kid LAROI",
        album: "F*CK LOVE 3",
        addedAt: "1 week ago",
        duration: "2:21",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "4",
        title: "Peaches",
        artist: "Justin Bieber",
        album: "Justice",
        addedAt: "1 week ago",
        duration: "3:18",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "5",
        title: "good 4 u",
        artist: "Olivia Rodrigo",
        album: "SOUR",
        addedAt: "2 weeks ago",
        duration: "2:58",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "6",
        title: "MONTERO",
        artist: "Lil Nas X",
        album: "MONTERO",
        addedAt: "2 weeks ago",
        duration: "2:18",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "7",
        title: "drivers license",
        artist: "Olivia Rodrigo",
        album: "SOUR",
        addedAt: "3 weeks ago",
        duration: "4:02",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "8",
        title: "Save Your Tears",
        artist: "The Weeknd",
        album: "After Hours",
        addedAt: "3 weeks ago",
        duration: "3:36",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "9",
        title: "Mood",
        artist: "24kGoldn",
        album: "El Dorado",
        addedAt: "1 month ago",
        duration: "2:21",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "10",
        title: "Watermelon Sugar",
        artist: "Harry Styles",
        album: "Fine Line",
        addedAt: "1 month ago",
        duration: "2:54",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "11",
        title: "Positions",
        artist: "Ariana Grande",
        album: "Positions",
        addedAt: "1 month ago",
        duration: "2:52",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "12",
        title: "Therefore I Am",
        artist: "Billie Eilish",
        album: "Happier Than Ever",
        addedAt: "2 months ago",
        duration: "2:54",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "13",
        title: "Heat Waves",
        artist: "Glass Animals",
        album: "Dreamland",
        addedAt: "2 months ago",
        duration: "3:58",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "14",
        title: "As It Was",
        artist: "Harry Styles",
        album: "Harry's House",
        addedAt: "2 months ago",
        duration: "2:37",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "15",
        title: "Bad Habit",
        artist: "Steve Lacy",
        album: "Gemini Rights",
        addedAt: "3 months ago",
        duration: "3:52",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "16",
        title: "About Damn Time",
        artist: "Lizzo",
        album: "Special",
        addedAt: "3 months ago",
        duration: "3:13",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "17",
        title: "Running Up That Hill",
        artist: "Kate Bush",
        album: "Hounds of Love",
        addedAt: "3 months ago",
        duration: "4:58",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "18",
        title: "Anti-Hero",
        artist: "Taylor Swift",
        album: "Midnights",
        addedAt: "4 months ago",
        duration: "3:20",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "19",
        title: "Escapism.",
        artist: "RAYE",
        album: "My 21st Century Blues",
        addedAt: "4 months ago",
        duration: "3:28",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "20",
        title: "Flowers",
        artist: "Miley Cyrus",
        album: "Endless Summer Vacation",
        addedAt: "5 months ago",
        duration: "3:20",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "21",
        title: "Unholy",
        artist: "Sam Smith",
        album: "Gloria",
        addedAt: "5 months ago",
        duration: "2:37",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "22",
        title: "Creepin'",
        artist: "Metro Boomin",
        album: "Heroes & Villains",
        addedAt: "5 months ago",
        duration: "3:22",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
    ],
  },
  {
    id: "2",
    name: "Late Night Drive",
    collaborators: ["xevrion"],
    coverUrl: "https://imgs.search.brave.com/sZN1oHQ0mAxRp9Xwi1g7q0vyBWPDocLlx9PioN5Cqc8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90ZW1w/bGF0ZS5jYW52YS5j/b20vRUFFZGUwMWkw/T0EvMS8wLzE2MDB3/LUs0a3p5MjJJTDRB/LmpwZw",
    tracks: [
      {
        id: "23",
        title: "Midnight Rain",
        artist: "Taylor Swift",
        album: "Midnights",
        addedAt: "1 day ago",
        duration: "3:03",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "24",
        title: "Cruel Summer",
        artist: "Taylor Swift",
        album: "Lover",
        addedAt: "2 days ago",
        duration: "2:58",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "25",
        title: "Stargazing",
        artist: "Travis Scott",
        album: "Astroworld",
        addedAt: "4 days ago",
        duration: "3:42",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "26",
        title: "Night Owl",
        artist: "Galimatias",
        album: "Fantasy",
        addedAt: "1 week ago",
        duration: "3:15",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "27",
        title: "After Dark",
        artist: "Mr.Kitty",
        album: "After Dark",
        addedAt: "1 week ago",
        duration: "4:09",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "28",
        title: "Redbone",
        artist: "Childish Gambino",
        album: '"Awaken, My Love!"',
        addedAt: "2 weeks ago",
        duration: "5:27",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "29",
        title: "Nights",
        artist: "Frank Ocean",
        album: "Blonde",
        addedAt: "2 weeks ago",
        duration: "5:07",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "30",
        title: "Die For You",
        artist: "The Weeknd",
        album: "Starboy",
        addedAt: "3 weeks ago",
        duration: "4:21",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "31",
        title: "Best Part",
        artist: "Daniel Caesar",
        album: "Freudian",
        addedAt: "1 month ago",
        duration: "3:31",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "32",
        title: "Ivy",
        artist: "Frank Ocean",
        album: "Blonde",
        addedAt: "1 month ago",
        duration: "4:09",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
    ],
  },
  {
    id: "3",
    name: "Workout Mix",
    collaborators: ["xevrion", "chishxd", "nyamp"],
    coverUrl: "https://imgs.search.brave.com/sZN1oHQ0mAxRp9Xwi1g7q0vyBWPDocLlx9PioN5Cqc8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90ZW1w/bGF0ZS5jYW52YS5j/b20vRUFFZGUwMWkw/T0EvMS8wLzE2MDB3/LUs0a3p5MjJJTDRB/LmpwZw",
    tracks: [
      {
        id: "33",
        title: "HUMBLE.",
        artist: "Kendrick Lamar",
        album: "DAMN.",
        addedAt: "4 days ago",
        duration: "2:57",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "34",
        title: "SICKO MODE",
        artist: "Travis Scott",
        album: "ASTROWORLD",
        addedAt: "1 week ago",
        duration: "5:13",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "35",
        title: "Power",
        artist: "Kanye West",
        album: "My Beautiful Dark Twisted Fantasy",
        addedAt: "1 week ago",
        duration: "4:52",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "36",
        title: "Gods Plan",
        artist: "Drake",
        album: "Scorpion",
        addedAt: "2 weeks ago",
        duration: "3:18",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "37",
        title: "All The Stars",
        artist: "Kendrick Lamar",
        album: "Black Panther",
        addedAt: "2 weeks ago",
        duration: "3:52",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "38",
        title: "HIGHEST IN THE ROOM",
        artist: "Travis Scott",
        album: "JACKBOYS",
        addedAt: "3 weeks ago",
        duration: "2:58",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "39",
        title: "Lucid Dreams",
        artist: "Juice WRLD",
        album: "Goodbye & Good Riddance",
        addedAt: "1 month ago",
        duration: "3:59",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "40",
        title: "Rockstar",
        artist: "Post Malone",
        album: "Beerbongs & Bentleys",
        addedAt: "1 month ago",
        duration: "3:39",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
    ],
  },
  {
    id: "4",
    name: "Indie Mornings",
    collaborators: ["xevrion", "chishxd"],
    coverUrl: "https://imgs.search.brave.com/sZN1oHQ0mAxRp9Xwi1g7q0vyBWPDocLlx9PioN5Cqc8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90ZW1w/bGF0ZS5jYW52YS5j/b20vRUFFZGUwMWkw/T0EvMS8wLzE2MDB3/LUs0a3p5MjJJTDRB/LmpwZw",
      tracks: [
      {
        id: "41",
        title: "Electric Feel",
        artist: "MGMT",
        album: "Oracular Spectacular",
        addedAt: "2 days ago",
        duration: "3:49",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "42",
        title: "Do I Wanna Know?",
        artist: "Arctic Monkeys",
        album: "AM",
        addedAt: "5 days ago",
        duration: "4:32",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "43",
        title: "R U Mine?",
        artist: "Arctic Monkeys",
        album: "AM",
        addedAt: "1 week ago",
        duration: "3:21",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "44",
        title: "Fluorescent Adolescent",
        artist: "Arctic Monkeys",
        album: "Suck It and See",
        addedAt: "2 weeks ago",
        duration: "2:57",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "45",
        title: "Take Me Out",
        artist: "Franz Ferdinand",
        album: "Franz Ferdinand",
        addedAt: "3 weeks ago",
        duration: "3:57",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "46",
        title: "Mr. Brightside",
        artist: "The Killers",
        album: "Hot Fuss",
        addedAt: "1 month ago",
        duration: "3:42",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "47",
        title: "Reptilia",
        artist: "The Strokes",
        album: "Room on Fire",
        addedAt: "1 month ago",
        duration: "3:36",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "48",
        title: "Last Nite",
        artist: "The Strokes",
        album: "Is This It",
        addedAt: "2 months ago",
        duration: "3:13",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
    ],
  },
  {
    id: "5",
    name: "Lo-fi Study",
    collaborators: ["xevrion"],
    coverUrl: "https://imgs.search.brave.com/sZN1oHQ0mAxRp9Xwi1g7q0vyBWPDocLlx9PioN5Cqc8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90ZW1w/bGF0ZS5jYW52YS5j/b20vRUFFZGUwMWkw/T0EvMS8wLzE2MDB3/LUs0a3p5MjJJTDRB/LmpwZw",
    tracks: [
      {
        id: "49",
        title: "Snowfall",
        artist: "Oneheart",
        album: "Snowfall",
        addedAt: "1 day ago",
        duration: "2:06",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "50",
        title: "Clair de Lune",
        artist: "Debussy",
        album: "Suite bergamasque",
        addedAt: "3 days ago",
        duration: "4:52",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "51",
        title: "Sleepy Fish",
        artist: "Sleepy Fish",
        album: "Deep Sea",
        addedAt: "1 week ago",
        duration: "3:12",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "52",
        title: "Rainy Day",
        artist: "j'san",
        album: "Soft Rains",
        addedAt: "2 weeks ago",
        duration: "2:54",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "53",
        title: "Counting Stars",
        artist: "idealism",
        album: "Pastel",
        addedAt: "3 weeks ago",
        duration: "3:08",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
    ],
  },
  {
    id: "6",
    name: "2000s Throwback",
    collaborators: ["xevrion", "nyamp"],
    coverUrl: "https://imgs.search.brave.com/sZN1oHQ0mAxRp9Xwi1g7q0vyBWPDocLlx9PioN5Cqc8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90ZW1w/bGF0ZS5jYW52YS5j/b20vRUFFZGUwMWkw/T0EvMS8wLzE2MDB3/LUs0a3p5MjJJTDRB/LmpwZw",
    tracks: [
      {
        id: "54",
        title: "Numb",
        artist: "Linkin Park",
        album: "Meteora",
        addedAt: "2 days ago",
        duration: "3:05",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "55",
        title: "In The End",
        artist: "Linkin Park",
        album: "Hybrid Theory",
        addedAt: "4 days ago",
        duration: "3:36",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "56",
        title: "Boulevard of Broken Dreams",
        artist: "Green Day",
        album: "American Idiot",
        addedAt: "1 week ago",
        duration: "4:20",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "57",
        title: "Welcome to the Black Parade",
        artist: "My Chemical Romance",
        album: "The Black Parade",
        addedAt: "2 weeks ago",
        duration: "5:11",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "58",
        title: "Sugar We're Goin Down",
        artist: "Fall Out Boy",
        album: "From Under the Cork Tree",
        addedAt: "3 weeks ago",
        duration: "3:49",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "59",
        title: "Dance Dance",
        artist: "Fall Out Boy",
        album: "From Under the Cork Tree",
        addedAt: "1 month ago",
        duration: "3:04",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "60",
        title: "Misery Business",
        artist: "Paramore",
        album: "Riot!",
        addedAt: "1 month ago",
        duration: "3:31",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
    ],
  },
  {
    id: "7",
    name: "Soul & R&B",
    collaborators: ["xevrion", "chishxd"],
    coverUrl: "https://imgs.search.brave.com/sZN1oHQ0mAxRp9Xwi1g7q0vyBWPDocLlx9PioN5Cqc8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90ZW1w/bGF0ZS5jYW52YS5j/b20vRUFFZGUwMWkw/T0EvMS8wLzE2MDB3/LUs0a3p5MjJJTDRB/LmpwZw",
    tracks: [
      {
        id: "61",
        title: "No Church In The Wild",
        artist: "JAY-Z & Kanye",
        album: "Watch the Throne",
        addedAt: "1 day ago",
        duration: "4:32",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
      },
      {
        id: "62",
        title: "Pyramids",
        artist: "Frank Ocean",
        album: "channel ORANGE",
        addedAt: "3 days ago",
        duration: "9:52",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "63",
        title: "Superstar",
        artist: "Lauryn Hill",
        album: "The Miseducation",
        addedAt: "1 week ago",
        duration: "4:05",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "64",
        title: "Golden",
        artist: "Jill Scott",
        album: "Who Is Jill Scott?",
        addedAt: "2 weeks ago",
        duration: "4:38",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
      {
        id: "65",
        title: "No Ordinary Love",
        artist: "Sade",
        album: "Love Deluxe",
        addedAt: "1 month ago",
        duration: "4:44",
        coverUrl: "https://trendybeatz.com/images/Justin-Bieber-Ft-Burna-Boy-Loved-By-You-Artwork.jpg",
        },
    ],
  },
];

export const MOCK_CURRENT_TRACK = MOCK_PLAYLISTS[0].tracks[0];
