import type { Playlist } from '../types/music'

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: '1',
    name: 'Chill Songs',
    collaborators: ['xevrion', 'chishxd'],
    tracks: [
      { id: '1',  title: 'Blinding Lights',       artist: 'The Weeknd',       album: 'After Hours',        addedAt: '3 days ago',   duration: '3:20' },
      { id: '2',  title: 'Levitating',             artist: 'Dua Lipa',         album: 'Future Nostalgia',   addedAt: '5 days ago',   duration: '3:23' },
      { id: '3',  title: 'Stay',                   artist: 'The Kid LAROI',    album: 'F*CK LOVE 3',        addedAt: '1 week ago',   duration: '2:21' },
      { id: '4',  title: 'Peaches',                artist: 'Justin Bieber',    album: 'Justice',            addedAt: '1 week ago',   duration: '3:18' },
      { id: '5',  title: 'good 4 u',               artist: 'Olivia Rodrigo',   album: 'SOUR',               addedAt: '2 weeks ago',  duration: '2:58' },
      { id: '6',  title: 'MONTERO',                artist: 'Lil Nas X',        album: 'MONTERO',            addedAt: '2 weeks ago',  duration: '2:18' },
      { id: '7',  title: 'drivers license',        artist: 'Olivia Rodrigo',   album: 'SOUR',               addedAt: '3 weeks ago',  duration: '4:02' },
      { id: '8',  title: 'Save Your Tears',        artist: 'The Weeknd',       album: 'After Hours',        addedAt: '3 weeks ago',  duration: '3:36' },
      { id: '9',  title: 'Mood',                   artist: '24kGoldn',         album: 'El Dorado',          addedAt: '1 month ago',  duration: '2:21' },
      { id: '10', title: 'Watermelon Sugar',       artist: 'Harry Styles',     album: 'Fine Line',          addedAt: '1 month ago',  duration: '2:54' },
      { id: '11', title: 'Positions',              artist: 'Ariana Grande',    album: 'Positions',          addedAt: '1 month ago',  duration: '2:52' },
      { id: '12', title: 'Therefore I Am',         artist: 'Billie Eilish',    album: 'Happier Than Ever',  addedAt: '2 months ago', duration: '2:54' },
      { id: '13', title: 'Heat Waves',             artist: 'Glass Animals',    album: 'Dreamland',          addedAt: '2 months ago', duration: '3:58' },
      { id: '14', title: 'As It Was',              artist: 'Harry Styles',     album: "Harry's House",      addedAt: '2 months ago', duration: '2:37' },
      { id: '15', title: 'Bad Habit',              artist: 'Steve Lacy',       album: 'Gemini Rights',      addedAt: '3 months ago', duration: '3:52' },
      { id: '16', title: 'About Damn Time',        artist: 'Lizzo',            album: 'Special',            addedAt: '3 months ago', duration: '3:13' },
      { id: '17', title: 'Running Up That Hill',   artist: 'Kate Bush',        album: 'Hounds of Love',     addedAt: '3 months ago', duration: '4:58' },
      { id: '18', title: 'Anti-Hero',              artist: 'Taylor Swift',     album: 'Midnights',          addedAt: '4 months ago', duration: '3:20' },
      { id: '19', title: 'Escapism.',              artist: 'RAYE',             album: 'My 21st Century Blues', addedAt: '4 months ago', duration: '3:28' },
      { id: '20', title: 'Flowers',                artist: 'Miley Cyrus',      album: 'Endless Summer Vacation', addedAt: '5 months ago', duration: '3:20' },
      { id: '21', title: 'Unholy',                 artist: 'Sam Smith',        album: 'Gloria',             addedAt: '5 months ago', duration: '2:37' },
      { id: '22', title: 'Creepin\'',              artist: 'Metro Boomin',     album: 'Heroes & Villains',  addedAt: '5 months ago', duration: '3:22' },
    ],
  },
  {
    id: '2',
    name: 'Late Night Drive',
    collaborators: ['xevrion'],
    tracks: [
      { id: '23', title: 'Midnight Rain',          artist: 'Taylor Swift',     album: 'Midnights',          addedAt: '1 day ago',    duration: '3:03' },
      { id: '24', title: 'Cruel Summer',           artist: 'Taylor Swift',     album: 'Lover',              addedAt: '2 days ago',   duration: '2:58' },
      { id: '25', title: 'Stargazing',             artist: 'Travis Scott',     album: 'Astroworld',         addedAt: '4 days ago',   duration: '3:42' },
      { id: '26', title: 'Night Owl',              artist: 'Galimatias',       album: 'Fantasy',            addedAt: '1 week ago',   duration: '3:15' },
      { id: '27', title: 'After Dark',             artist: 'Mr.Kitty',         album: 'After Dark',         addedAt: '1 week ago',   duration: '4:09' },
      { id: '28', title: 'Redbone',                artist: 'Childish Gambino', album: '"Awaken, My Love!"', addedAt: '2 weeks ago',  duration: '5:27' },
      { id: '29', title: 'Nights',                 artist: 'Frank Ocean',      album: 'Blonde',             addedAt: '2 weeks ago',  duration: '5:07' },
      { id: '30', title: 'Die For You',            artist: 'The Weeknd',       album: 'Starboy',            addedAt: '3 weeks ago',  duration: '4:21' },
      { id: '31', title: 'Best Part',              artist: 'Daniel Caesar',    album: 'Freudian',           addedAt: '1 month ago',  duration: '3:31' },
      { id: '32', title: 'Ivy',                    artist: 'Frank Ocean',      album: 'Blonde',             addedAt: '1 month ago',  duration: '4:09' },
    ],
  },
  {
    id: '3',
    name: 'Workout Mix',
    collaborators: ['xevrion', 'chishxd', 'nyamp'],
    tracks: [
      { id: '33', title: 'HUMBLE.',                artist: 'Kendrick Lamar',   album: 'DAMN.',              addedAt: '4 days ago',   duration: '2:57' },
      { id: '34', title: 'SICKO MODE',             artist: 'Travis Scott',     album: 'ASTROWORLD',         addedAt: '1 week ago',   duration: '5:13' },
      { id: '35', title: 'Power',                  artist: 'Kanye West',       album: 'My Beautiful Dark Twisted Fantasy', addedAt: '1 week ago', duration: '4:52' },
      { id: '36', title: 'Gods Plan',              artist: 'Drake',            album: 'Scorpion',           addedAt: '2 weeks ago',  duration: '3:18' },
      { id: '37', title: 'All The Stars',          artist: 'Kendrick Lamar',   album: 'Black Panther',      addedAt: '2 weeks ago',  duration: '3:52' },
      { id: '38', title: 'HIGHEST IN THE ROOM',    artist: 'Travis Scott',     album: 'JACKBOYS',           addedAt: '3 weeks ago',  duration: '2:58' },
      { id: '39', title: 'Lucid Dreams',           artist: 'Juice WRLD',       album: 'Goodbye & Good Riddance', addedAt: '1 month ago', duration: '3:59' },
      { id: '40', title: 'Rockstar',               artist: 'Post Malone',      album: 'Beerbongs & Bentleys', addedAt: '1 month ago', duration: '3:39' },
    ],
  },
  {
    id: '4',
    name: 'Indie Mornings',
    collaborators: ['xevrion', 'chishxd'],
    tracks: [
      { id: '41', title: 'Electric Feel',          artist: 'MGMT',             album: 'Oracular Spectacular', addedAt: '2 days ago', duration: '3:49' },
      { id: '42', title: 'Do I Wanna Know?',       artist: 'Arctic Monkeys',   album: 'AM',                 addedAt: '5 days ago',   duration: '4:32' },
      { id: '43', title: 'R U Mine?',              artist: 'Arctic Monkeys',   album: 'AM',                 addedAt: '1 week ago',   duration: '3:21' },
      { id: '44', title: 'Fluorescent Adolescent', artist: 'Arctic Monkeys',   album: 'Suck It and See',    addedAt: '2 weeks ago',  duration: '2:57' },
      { id: '45', title: 'Take Me Out',            artist: 'Franz Ferdinand',  album: 'Franz Ferdinand',    addedAt: '3 weeks ago',  duration: '3:57' },
      { id: '46', title: 'Mr. Brightside',         artist: 'The Killers',      album: 'Hot Fuss',           addedAt: '1 month ago',  duration: '3:42' },
      { id: '47', title: 'Reptilia',               artist: 'The Strokes',      album: 'Room on Fire',       addedAt: '1 month ago',  duration: '3:36' },
      { id: '48', title: 'Last Nite',              artist: 'The Strokes',      album: 'Is This It',         addedAt: '2 months ago', duration: '3:13' },
    ],
  },
  {
    id: '5',
    name: 'Lo-fi Study',
    collaborators: ['xevrion'],
    tracks: [
      { id: '49', title: 'Snowfall',               artist: 'Øneheart',         album: 'Snowfall',           addedAt: '1 day ago',    duration: '2:06' },
      { id: '50', title: 'Clair de Lune',          artist: 'Debussy',          album: 'Suite bergamasque',  addedAt: '3 days ago',   duration: '4:52' },
      { id: '51', title: 'Sleepy Fish',            artist: 'Sleepy Fish',      album: 'Deep Sea',           addedAt: '1 week ago',   duration: '3:12' },
      { id: '52', title: 'Rainy Day',              artist: 'j\'san',           album: 'Soft Rains',         addedAt: '2 weeks ago',  duration: '2:54' },
      { id: '53', title: 'Counting Stars',         artist: 'idealism',         album: 'Pastel',             addedAt: '3 weeks ago',  duration: '3:08' },
    ],
  },
  {
    id: '6',
    name: '2000s Throwback',
    collaborators: ['xevrion', 'nyamp'],
    tracks: [
      { id: '54', title: 'Numb',                   artist: 'Linkin Park',      album: 'Meteora',            addedAt: '2 days ago',   duration: '3:05' },
      { id: '55', title: 'In The End',             artist: 'Linkin Park',      album: 'Hybrid Theory',      addedAt: '4 days ago',   duration: '3:36' },
      { id: '56', title: 'Boulevard of Broken Dreams', artist: 'Green Day',   album: 'American Idiot',     addedAt: '1 week ago',   duration: '4:20' },
      { id: '57', title: 'Welcome to the Black Parade', artist: 'My Chemical Romance', album: 'The Black Parade', addedAt: '2 weeks ago', duration: '5:11' },
      { id: '58', title: 'Sugar We\'re Goin Down', artist: 'Fall Out Boy',     album: 'From Under the Cork Tree', addedAt: '3 weeks ago', duration: '3:49' },
      { id: '59', title: 'Dance Dance',            artist: 'Fall Out Boy',     album: 'From Under the Cork Tree', addedAt: '1 month ago', duration: '3:04' },
      { id: '60', title: 'Misery Business',        artist: 'Paramore',         album: 'Riot!',              addedAt: '1 month ago',  duration: '3:31' },
    ],
  },
  {
    id: '7',
    name: 'Soul & R&B',
    collaborators: ['xevrion', 'chishxd'],
    tracks: [
      { id: '61', title: 'No Church In The Wild',  artist: 'JAY-Z & Kanye',   album: 'Watch the Throne',   addedAt: '1 day ago',    duration: '4:32' },
      { id: '62', title: 'Pyramids',               artist: 'Frank Ocean',      album: 'channel ORANGE',     addedAt: '3 days ago',   duration: '9:52' },
      { id: '63', title: 'Superstar',              artist: 'Lauryn Hill',      album: 'The Miseducation',   addedAt: '1 week ago',   duration: '4:05' },
      { id: '64', title: 'Golden',                 artist: 'Jill Scott',       album: 'Who Is Jill Scott?', addedAt: '2 weeks ago',  duration: '4:38' },
      { id: '65', title: 'No Ordinary Love',       artist: 'Sade',             album: 'Love Deluxe',        addedAt: '1 month ago',  duration: '4:44' },
    ],
  },
]

export const MOCK_CURRENT_TRACK = MOCK_PLAYLISTS[0].tracks[0]
